CREATE TABLE `api_tokens` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`owner_id` integer NOT NULL,`user_id` integer,`token_prefix` text NOT NULL,`token_hash` text NOT NULL,`salt` text NOT NULL,`name` text,`scope` text,`expires_at` datetime,`last_used_at` datetime,`disabled` numeric NOT NULL DEFAULT false);
CREATE UNIQUE INDEX `idx_api_tokens_token_hash` ON `api_tokens`(`token_hash`);
CREATE INDEX `idx_api_tokens_token_prefix` ON `api_tokens`(`token_prefix`);
CREATE INDEX `idx_api_tokens_user_id` ON `api_tokens`(`user_id`);
CREATE INDEX `idx_api_tokens_owner_id` ON `api_tokens`(`owner_id`);
CREATE INDEX `idx_api_tokens_deleted_at` ON `api_tokens`(`deleted_at`);
CREATE TABLE `companies` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`address1` text,`address2` text,`background` text,`contact_invoice` text,`default_tax_rate` decimal(20,8),`invoice_currency` text,`invoice_exemption_reason` text,`invoice_footer` text,`invoice_opening` text,`invoice_tax_type` text,`customer_number` text,`country` text,`name` text,`city` text,`owner_id` integer,`zip` text,`invoice_email` text,`supplier_number` text,`vat_id` text);
CREATE INDEX `idx_companies_deleted_at` ON `companies`(`deleted_at`);
CREATE TABLE `contact_infos` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`owner_id` integer,`parent_id` integer,`parent_type` text,`type` text,`label` text,`value` text);
CREATE INDEX `idx_contact_infos_type` ON `contact_infos`(`type`);
CREATE INDEX `idx_contact_parent` ON `contact_infos`(`parent_id`,`parent_type`);
CREATE INDEX `idx_contact_infos_owner_id` ON `contact_infos`(`owner_id`);
CREATE INDEX `idx_contact_infos_deleted_at` ON `contact_infos`(`deleted_at`);
CREATE TABLE `invitations` (`id` integer PRIMARY KEY AUTOINCREMENT,`token` text,`email` text,`expires_at` datetime,`created_at` datetime);
CREATE UNIQUE INDEX `idx_invitations_token` ON `invitations`(`token`);
CREATE TABLE `letterhead_templates` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`owner_id` integer,`name` text,`page_width_cm` real,`page_height_cm` real,`pdf_path` text,`preview_page1_url` text,`preview_page2_url` text,`font_normal` text,`font_bold` text,`font_italic` text);
CREATE INDEX `idx_letterhead_templates_owner_id` ON `letterhead_templates`(`owner_id`);
CREATE INDEX `idx_letterhead_templates_deleted_at` ON `letterhead_templates`(`deleted_at`);
CREATE TABLE `invoices` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`company_id` integer,`contact_invoice` text,`counter` integer,`currency` text,`date` datetime,`due_date` datetime,`exemption_reason` text,`footer` text,`gross_total` text,`net_total` text,`number` text,`occurrence_date` datetime,`opening` text,`order_number` text,`owner_id` integer,`supplier_number` text,`tax_number` text,`tax_type` text,`status` text NOT NULL DEFAULT "draft",`issued_at` datetime,`paid_at` datetime,`voided_at` datetime,`template_id` integer,CONSTRAINT `fk_invoices_template` FOREIGN KEY (`template_id`) REFERENCES `letterhead_templates`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `fk_companies_invoices` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`),CONSTRAINT `chk_invoices_status` CHECK (status IN ('draft','issued','paid','voided')));
CREATE INDEX `idx_owner_status` ON `invoices`(`status`);
CREATE INDEX `idx_invoices_status` ON `invoices`(`status`);
CREATE INDEX `idx_invoices_deleted_at` ON `invoices`(`deleted_at`);
CREATE TABLE `invoicepositions` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`owner_id` integer,`invoice_id` integer,`position` integer,`unit_code` text,`text` text,`quantity` text,`tax_rate` text,`net_price` text,`gross_price` text,`line_total` text,CONSTRAINT `fk_invoices_invoice_positions` FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`));
CREATE TABLE `letterhead_regions` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`template_id` integer,`owner_id` integer,`kind` text,`page` integer,`x_cm` real,`y_cm` real,`width_cm` real,`height_cm` real,`h_align` text,`v_align` text,`font_name` text,`font_size_pt` real,`line_spacing` real,`has_page2` numeric NOT NULL DEFAULT false,`x2_cm` real,`y2_cm` real,`width2_cm` real,`height2_cm` real,CONSTRAINT `fk_letterhead_templates_regions` FOREIGN KEY (`template_id`) REFERENCES `letterhead_templates`(`id`) ON DELETE CASCADE);
CREATE UNIQUE INDEX `uniq_tpl_owner_kind` ON `letterhead_regions`(`template_id`,`owner_id`,`kind`);
CREATE INDEX `idx_regions_tpl_owner` ON `letterhead_regions`(`template_id`,`owner_id`);
CREATE TABLE `notes` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`owner_id` integer,`author_id` integer,`parent_id` integer,`parent_type` text,`title` text,`body` text,`tags` text,`edited_at` datetime);
CREATE INDEX `idx_notes_deleted_at` ON `notes`(`deleted_at`);
CREATE INDEX `idx_notes_author_id` ON `notes`(`author_id`);
CREATE TABLE `people` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`owner_id` integer,`name` text,`position` text,`e_mail` text,`company_id` integer,CONSTRAINT `fk_people_company` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`));
CREATE INDEX `idx_people_deleted_at` ON `people`(`deleted_at`);
CREATE TABLE `recent_views` (`user_id` integer NOT NULL,`entity_type` text NOT NULL,`entity_id` integer NOT NULL,`viewed_at` datetime NOT NULL);
CREATE INDEX `idx_user_viewed_at` ON `recent_views`(`viewed_at`);
CREATE INDEX `idx_user_view` ON `recent_views`(`user_id`,`entity_type`,`entity_id`);
CREATE TABLE `settings` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`owner_id` integer,`company_name` text,`invoice_contact` text,`invoice_email` text,`zip` text,`address1` text,`address2` text,`city` text,`country_code` text,`vat_id` text,`tax_number` text,`invoice_number_template` text,`use_local_counter` numeric,`bank_iban` text,`bank_name` text,`bank_bic` text,`customer_number_prefix` text,`customer_number_width` integer,`customer_number_counter` integer);
CREATE UNIQUE INDEX `idx_settings_owner_id` ON `settings`(`owner_id`);
CREATE INDEX `idx_settings_deleted_at` ON `settings`(`deleted_at`);
CREATE TABLE `signup_tokens` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`email` text NOT NULL,`token_hash` blob NOT NULL,`expires_at` datetime NOT NULL,`consumed_at` datetime,`password_hash` text NOT NULL);
CREATE INDEX `idx_signup_tokens_email` ON `signup_tokens`(`email`);
CREATE INDEX `idx_signup_tokens_deleted_at` ON `signup_tokens`(`deleted_at`);
CREATE UNIQUE INDEX `idx_signup_tokens_token_hash` ON `signup_tokens`(`token_hash`);
CREATE TABLE `tags` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`owner_id` integer,`name` text NOT NULL,`norm` text NOT NULL);
CREATE INDEX `idx_tag_owner_name` ON `tags`(`owner_id`,`name`);
CREATE UNIQUE INDEX `uniq_tag_per_owner` ON `tags`(`owner_id`,`norm`);
CREATE TABLE `tag_links` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`owner_id` integer NOT NULL,`tag_id` integer NOT NULL,`parent_type` text NOT NULL,`parent_id` integer NOT NULL,CONSTRAINT `fk_tag_links_tag` FOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`) ON DELETE CASCADE);
CREATE INDEX `idx_taglink_parent` ON `tag_links`(`parent_type`,`parent_id`);
CREATE INDEX `idx_taglink_tag` ON `tag_links`(`tag_id`);
CREATE UNIQUE INDEX `uniq_tag_parent` ON `tag_links`(`owner_id`,`tag_id`,`parent_type`,`parent_id`);
CREATE INDEX `idx_tag_links_deleted_at` ON `tag_links`(`deleted_at`);
CREATE TABLE `users` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`email` text NOT NULL,`full_name` text,`password` text NOT NULL,`password_reset_token` blob,`password_reset_expiry` datetime,`verified` numeric NOT NULL DEFAULT false,`last_login_at` datetime,`owner_id` integer);
CREATE UNIQUE INDEX `idx_users_email` ON `users`(`email`);
CREATE INDEX `idx_users_deleted_at` ON `users`(`deleted_at`);
